### ISSUE TITLE
list view button not working on samsung s6 edge plus

### ISSUE THREAD

**Issue by werdnanoslen** [werdnanoslen/rishwat#1]
@ahkazim can you please post a screenshot of which button isn't working and what happens when you try pressing it? Also mention what device you're using

**Comment by werdnanoslen** [comment]
cannot reproduce

**Comment by ahkazim** [comment]
![screenshot_20170212-174358](https://cloud.githubusercontent.com/assets/10159667/22866917/a1346d2e-f14b-11e6-9a11-49071a361b24.png)

What is the purpose of the button? 
On samsung s6 edge plus it does nothing

**Comment by werdnanoslen** [comment]
@ahkazim the button goes to a list view of reports vs a map view, i'll change this report to be device-specific, but I can't really do anything about it without logs. Can you plug your phone into a computer so you can get a log dump of the error and post here?
