### ISSUE TITLE
Search nearby without relying on place types

### ISSUE THREAD

**Issue by werdnanoslen** [werdnanoslen/rishwat#2]
Replace coordinates with something more useful.
@ahkazim if the app can't figure out the name or address of a place the person indicated, what information would be better for location than coordinates?

**Comment by werdnanoslen** [comment]
Consider using vector to nearest landmark https://developers.google.com/maps/documentation/javascript/places#place_search_requests

**Comment by ahkazim** [comment]
I agree with suggestion

**Comment by werdnanoslen** [comment]
^ Not the best fix, as API requires selecting a [type](https://developers.google.com/places/supported_types) of place before searching. This makes me want to find a replacement for Google Places that provides the same or better variety of places (governmental, commercial, social, natural, etc) that supports purely proximal (without selecting type) searches

**Comment by werdnanoslen** [comment]
Factual seems to be one common suggestion, but it has since closed that option. OpenStreetMaps also has a lot of data, but much of it is simple latlng nodes without any other information ([example](http://www.overpass-api.de/api/interpreter?data=[out:json];node(1098292345);out;)). In order to do any better, we will need to create a custom database of POIs with human-readable names to base vectors on. 

Until then, the types array is still not deprecated, nor is the `establishment` type, despite it being well past Google's [announcement](https://developers.google.com/maps/documentation/javascript/places#deprecation) they would be. When that time comes, update this section https://github.com/werdnanoslen/rishwat/blob/master/www/js/controllers/AddCtrl.js#L299
