### ISSUE TITLE
Make this repo public?

### ISSUE THREAD

**Issue by werdnanoslen** [werdnanoslen/rishwat#6]
@ahkazim any reason why we should keep this repo private? I'd like to work on this for the Mozilla Global Sprint today and tomorrow and for my local hackathon ATX Hack for Change, so it'd have to be public.

**Comment by ahkazim** [comment]
Sorry for the late reply. PhD work is taking a lot of time to respond to email properly.

As long as you give credit to everyone, you are free to use.

I hope your hack went went well, sorry for late reply.


With kind regards,
Ali Hussain Kazim


Please consider the environment before printing this e-mail.

________________________________

**Comment by werdnanoslen** [comment]
Absolutely, let's ensure everyone who contributes to this project is recognized and lauded
